workflows:
  expo-app:
    name: Expo Android Build
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas build -p android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
